Set Padding 0
Set Margin 60
Set MarginFill "#6B50FF"
Set Width 600
Set Height 1000

Type@1ms "PROMPT_COMMAND='' && PS1='> '"
Sleep 100ms
Enter
Sleep 100ms
Type@1ms "enable -d flyline"
Sleep 100ms
Enter
Sleep 100ms
Type@1ms "clear"
Sleep 100ms
Enter
Sleep 100ms
Type@1ms "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKL"
Enter
Sleep 100ms
Sleep 3s
